### ISSUE TITLE
New steam DNS entry

### ISSUE THREAD

**Issue by whiztech** [ti-mo/ansible-lanparty#10]
Hello..

I'm seeing new DNS entry for steam

valve1001.steampipe.steamcontent.com

**Comment by ti-mo** [comment]
Hi @whiztech 

Thanks for sharing! Looks like valve1000-valve1007 are existing records. I might not be able to get this tested over the weekend, so override `ns.spoof.services.steam.domains` for now (if you're using this repo).

Just to confirm, are you updating your client from Malaysia?

**Comment by ti-mo** [comment]
@whiztech Thanks again, this was fixed in 6b8b7b6
