### ISSUE TITLE
Similar project which might be useful

### ISSUE THREAD

**Issue by ypid** [ti-mo/ansible-lanparty#12]
Hi there,

Really interesting project! :wink:

I just wanted to drop a line and mention the DebOps Project as it also provide a few roles which do similar things then yours. Check: https://debops.org/status.html

Just in case you need more for your setup.

**Comment by ti-mo** [comment]
Hi @ypid, thanks! DebOps is an impressive project indeed, have used some of the roles in the past. There is a little bit of overlap, but most of this project's roles are very minimal and specific.

We'll see if they could be of any use in the future!

**Comment by ypid** [comment]
You are welcome. :wink:
