### ISSUE TITLE
Blizzard Updates not working

### ISSUE THREAD

**Issue by RobertJamesMichael** [ti-mo/ansible-lanparty#14]
Hi!
I have found a new blizzard DNS entry when downloading WOW: level3.blizzard.com
this redirects to CNAME: download.blizzard.com.c.footprint.net
I have configured the first one: level3.blizzard.com to the nGINx Server, it works but very slow and after some minutes it stops, also, blizzard tries to get the updates through:
blzddist1-a.akamaihd.net
blzddist2-a.akamaihd.net
but it is not working.

hope this can be solved, maybe blizzard began to use SSL (I don't know how to check that).

**Comment by fsalazar1977** [comment]
It seems that Steam stopped working also...

**Comment by ti-mo** [comment]
Hi @fsalazar1977, sorry this took so long. I thought we stumbled upon a limitation in Nginx, but setting the following in the Blizzard location should fix this:

`proxy_hide_header ETag;`

You can re-enable slicing once again once this is set. This has been fixed in f105129.
