### ISSUE TITLE
Twitch caching no longer works

### ISSUE THREAD

**Issue by gergc** [ti-mo/ansible-lanparty#16]
Just a FYI - Twitch caching no longer works due to HTTPS being used.

**Comment by ti-mo** [comment]
@gergc please see https://github.com/ti-mo/ansible-lanparty/issues/11
The role is kept around in the repo for reference purposes, or for environments that have control over their clients (ie. adding self-signed twitch cert).

**Comment by gergc** [comment]
Ah, sorry! I didn't look at the closed issues because I'm a dummy. Thanks!

**Comment by ti-mo** [comment]
@gergc This was addressed in 3e4b32e
