### ISSUE TITLE
Steam site not catching 100%

### ISSUE THREAD

**Issue by RobertJamesMichael** [ti-mo/ansible-lanparty#21]
Hi Temo, I have been testing steam (dota2); all traffic is passing through nGinx but not all is being cached, it seems that some parts are ignored. After downloading the complete game, the size of the Steam depot file is (approximately) the half size of the game, checked all the client traffic and it passes over nGinx, some idea whats is happening?

**Comment by ti-mo** [comment]
Hi @fasa1977. Large downloads on the internet are usually compressed to reduce bandwidth (and storage) requirements and are de-compressed on the client. (You could have compared network statistics of a client machine against the Dota2 folder on the client)

**Comment by ekhoury2000** [comment]
Dear Fasa,

@fasa1977 i was wondering is you server caching steam downloads perfectly? did u manage to cache any other games or game clients like blizzard? etc...

I am very interested in creating such servers, please let me know,

Elie
