### ISSUE TITLE
Steam and Games Repository

### ISSUE THREAD

**Issue by ekhoury2000** [ti-mo/ansible-lanparty#26]
Dear Timo,

I was looking at your work, and it seems very interesting.

I was wondering if i could use some of it to create a cache server for steam, blizzard, etc...

Anything that could help me achieve what i want is highly appreciated,

Thanks in advance,

Elie

**Comment by ti-mo** [comment]
Hi @ekhoury2000

Yes, [lp-depot](https://github.com/ti-mo/ansible-lanparty/tree/master/lp-depot) is our cache implementation. It assumes you're familiar with Linux, systems and network administration in general, Nginx and Ansible. However, providing help on these topics is far beyond the scope of this repository.

I agree that documentation is lacking, but the implementation itself aims to be as clear as possible. If you have any *specific* questions or issues, feel free to add them to the issue tracker, but keep in mind _this is not a forum_. If you're looking for a more user-friendly alternative based on this project, check out [qcacher](https://github.com/Q-Con/qcacher). You'll find that far easier to get started with.

Thanks for your interest, good luck!
